apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: Krateo sample burger template
  annotations:
    title: Krateo sample burger template
    description: delicious!
    owner: mauro.sala@kiratech.it
    icon: fa-solid fa-burger
  labels:
    tags:
    - burger
    - chips
    - krateo
spec:
  widgets:
  - title: Customer
    properties:
      name:
        title: customer name
        required: true
      age:
        title: age
        type: number
        description: your age
      creditCard:
        title: credit card
        required: true
        type: password
      
  - title: Starter
    box: beautiful start
    properties:
      snack:
        title: snack
        description: snack
        required: false
        type: radio
        values:
        - nuggets
        - chicken wings
        - cheese
  - title: Main Course
  - title: Dessert
