apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: Krateo sample burger template
  annotations:
    title: Krateo sample burger template
    description: delicious!
    owner: mauro.sala@kiratech.it
    icon: fa-solid fa-burger
  labels:
    tags:
      - burger
      - chips
      - krateo
spec:
  widgets:
    - title: Customer
      properties:
        name:
          title: customer name
          required: true
        age:
          title: age
          type: number
          description: your age
        creditCard:
          title: credit card
          required: true
          type: password

    - title: Starter
      box: beautiful start
      boxStyle: success
      properties:
        snack:
          title: snack
          description: snack
          required: false
          type: radio
          values:
            - nuggets
            - chicken wings
            - cheese
    - title: Main Course
      properties:
        burger:
          title: burger
          description: make a choice
          required: true
          type: radio
          values:
            - title: classic
              value: classic
            - title: egg burger
              description: with eggs
              value: egg
            - title: chicken burger
              value: chicken
            - title: beast burger
              description: 400g of meat
              value: beast
        extraCheese:
          title: extra cheese
          type: toggle
          dafault: false
          info: https://kiratech.it
        chips:
          title: chips
          type: radio
          default: standard
          values:
            - standard
            - with bacon
            - with cheese
            - with cheese and bacon
        sauce:
          title: sauce
          values:
            - ""
            - ketchup
            - mayo
            - barbecue
    - title: Dessert
      box: sweet end
      boxStyle: info
      properties:
        cake:
          title: cake
          values:
            - ""
            - title: cheese cake
              value: cheese cake
              cost: 10
            - oreo cake
            - strudel
        notes:
          title: notes
          type: textarea
