apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: Krateo burger template
  annotations:
    title: Krateo burger template
    description: delicious!
    owner: mauro.sala@kiratech.it
    icon: fa-solid fa-burger
  labels:
    tags:
      - burger
      - chips
      - krateo
spec:
  widgets:
    - title: Customer
      description: burger Customer
      properties:
        name:
          title: customer name
          description: your name
          required: true
        age:
          title: customer age
          description: your age
          type: number
        creditCard:
          title: customer credit card
          description: your credit card
          required: true
          type: password
    - title: Starter
      box: beautiful start
      properties:
        snack:
          title: snack
          required: false
          type: radio
          values:
            - title: nuggets
              value: nuggets
            - title: chicken wings
              value: wings
            - title: cheese snack
              value: cheese snack
    - title: Main Course
      properties:
        burger:
          title: burger
          description: your burger
          required: true
          type: radio
          values:
            - title: classic burger
              value: classic
            - title: egg burger
              description: with 2 eggs
              value: egg
            - title: chicken burger
              value: chicken
            - title: beast burger
              description: 400g of meat\nsecond line
              value: beast
        extraCheese:
          title: extra cheese
          description: extra cheese
          required: false
          type: toggle
        chips:
          title: chips
          type: radio
          default: standard
          values:
            - standard
            - with bacon
            - with cheese
            - with cheese and bacon
        sauce:
          title: sauce
          values:
            - ""
            - ketchup
            - mayo
            - barbecue
    - title: Drinks
    - title: Dessert
