apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: Krateo burger template
  annotations:
    title: Krateo burger template
    description: delicious!
    owner: mauro.sala@kiratech.it
    icon: fa-solid fa-burger
  labels:
    tags:
      - burger
      - chips
      - krateo
spec:
  defaults:
    organizationName: krateoplatformops
    repositoryName: test-{name}
  widgets:
    - title: Customer
      description: burger Customer
      properties:
        name:
          title: customer name
          description: your name
          required: true
        age:
          title: customer age
          description: your age
          type: number
          disabled: true
        creditCard:
          title: customer credit card
          description: your credit card
          required: true
          type: password
    - title: Starter
      box: beautiful start
      properties:
        snack:
          title: snack
          required: false
          disabled: true
          type: radio
          values:
            - title: nuggets
              value: nuggets
            - title: chicken wings
              value: wings
            - title: cheese snack
              value: cheese snack    
    - title: Main Course
      properties:
        burger:
          title: burger
          description: your burger
          required: true
          type: radio
          values:
            - title: classic burger
              value: classic
              cost: 8
            - title: egg burger
              description: with 2 eggs
              value: egg
              cost: 9
            - title: chicken burger
              value: chicken
              cost: 8
            - title: beast burger
              description: 400g of meat\nsecond line
              value: beast
              cost: 15
        extraCheese:
          title: extra cheese
          description: extra cheese
          required: false
          disabled: true
          type: toggle
        chips:
          title: chips
          type: radio
          default: standard
          values:
            - standard
            - with bacon
            - with cheese
            - with cheese and bacon
        sauce:
          title: sauce
          values:
            - ""
            - ketchup
            - mayo
            - barbecue
    - title: Drinks
      box: drinks
      boxStyle: warning
      properties:
        non-alcoholic:
          title: non-alcoholic drinks
          type: radio
          values:
            - coke
            - fanta
            - sprite
        alcoholic:
          title: alcoholic drinks
          default: beer
          values:
            - ""
            - beer
            - wine
            - vodka
    - title: Dessert
      box: sweet end
      boxStyle: info
      properties:
        cake:
          title: cake
          disabled: true
          values:
            - ""
            - title: cheesecake
              value: cheesecake
              cost: 5
            - oreo cake
            - strudel
        notes:
          title: notes
          type: textarea
          disabled: true
    - title: Ice Cream
      properties:
        flavors:
          title: ice cream flavors
          type: multiple
          default: chocolate
          values:
          - title: chocolate
            value: chocolate
            cost: 1
          - title: cream
            value: cream
            cost: 2
          - title: mint
            value: mint
            cost: 3
          - title: lemon
            value: lemon
            cost: 4
          - title: stracciatella
            value: stracciatella
            description: milk + choco
            cost: 5
