apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: Krateo burger template
  annotations:
    title: Krateo burger template
    description: delicious!
    owner: mauro.sala@kiratech.it
    icon: fa-solid fa-burger
  labels:
    tags:
      - burger
      - chips
      - krateo
spec:
  widgets:
    - title: Customer
      description: burger Customer
      properties:
        name:
          title: customer name
          description: your name
          required: true
        age:
          title: customer age
          description: your age
        creditCard:
          title: customer credit card
          description: your credit card
          required: true
    - title: Starter
    - title: Main Course
    - title: Drinks
    - title: Dessert
